export const GameStatuses = {
  STOPPED: 'STOPPED',
  INITIALIZING: 'INITIALIZING',
  STARTING_NEW_ROUND: 'STARTING_NEW_ROUND',
  PLAYING: 'PLAYING',
  SHOWING_INTERLUDE: 'SHOWING_INTERLUDE',
  ENDING_GAME: 'ENDING_GAME',
  SHOWING_RESULT: 'SHOWING_RESULT'
}
